### ISSUE TITLE
`add` builds but `remove` does not

### ISSUE THREAD

**Issue by krispya** [pmndrs/directed#11]
I got caught by a bug this evening because while `add` builds automatically, `remove` does not and you have to call `build` yourself for the command to commit. Is this the intended behavior?

**Comment by akdjr** [comment]
Unintended! add needs to change as the intention is for build to be called manually to support batching adds without building each time add is called.

**Comment by akdjr** [comment]
Fixed - add now follows the same behavior as remove.
